extends RefCounted

const BOARD_W = 7
const BOARD_H = 7
const MINE_COUNT = 9

const EXPLOSION_CENTER_DAMAGE = 4
const EXPLOSION_ADJACENT_DAMAGE = 2
const EXPLOSION_RADIUS_CHEBYSHEV = 1

const ENEMY_MAX_HP = 6
const ENEMY_ATTACK = 2
const ENEMY_COUNTDOWN = 3
const ENEMY_ZONE_MINES = 3

const PLAYER_MAX_HP = 10
const ACCIDENTAL_MINE_DAMAGE = 3

const GENERATION_MAX_TRIES = 100
const LONG_PRESS_SEC = 0.4
